import type { Article, Category, District } from '@/lib/types';

export const placeholderDistricts: District[] = [
  { id: '1', name: 'Bengaluru' },
  { id: '2', name: 'Mysuru' },
  { id: '3', name: 'Mangaluru' },
  { id: '4', name: 'Belagavi' },
  { id: '5', name: 'Hubballi-Dharwad' },
  { id: '6', name: 'Shivamogga' },
  { id: '7', name: 'Udupi' },
  { id: '8', name: 'Ballari' },
];

export const placeholderCategories: Category[] = [
  { id: '1', name: 'Politics', slug: 'politics' },
  { id: '2', name: 'Technology', slug: 'technology' },
  { id: '3', name: 'Sports', slug: 'sports' },
  { id: '4', name: 'Entertainment', slug: 'entertainment' },
  { id: '5', name: 'Business', slug: 'business' },
  { id: '6', name: 'Local News', slug: 'local-news' },
  { id: '7', name: 'General', slug: 'general' },
  { id: '8', name: 'Health', slug: 'health' },
  { id: '9', name: 'Science', slug: 'science' },
];

export const placeholderArticles: Article[] = [
  {
    id: '1',
    title: 'New Metro Line Inaugurated in Bengaluru',
    content: 'The new purple line extension was inaugurated today, promising to ease traffic congestion in the city. The line connects key tech parks and residential areas.',
    imageUrl: 'https://picsum.photos/800/600',
    "data-ai-hint": 'city train',
    author: 'Admin User',
    authorId: 'admin1',
    categoryIds: ['1', '6'],
    districtId: '1',
    status: 'published',
    publishedAt: new Date('2023-10-26T10:00:00Z'),
    createdAt: new Date('2023-10-26T09:00:00Z'),
    updatedAt: new Date('2023-10-26T09:30:00Z'),
    seo: { keywords: ['metro', 'bengaluru', 'traffic'], metaDescription: 'Read about the new metro line in Bengaluru.' },
    views: 1250,
  },
  {
    id: '2',
    title: 'Mysuru Dasara Preparations in Full Swing',
    content: 'The historic city of Mysuru is gearing up for its annual Dasara festival. The celebrations are expected to be grander than ever this year.',
    imageUrl: 'https://picsum.photos/800/600',
    "data-ai-hint": 'festival celebration',
    author: 'Editor User',
    authorId: 'editor1',
    categoryIds: ['4', '6'],
    districtId: '2',
    status: 'published',
    publishedAt: new Date('2023-10-25T14:00:00Z'),
    createdAt: new Date('2023-10-25T13:00:00Z'),
    updatedAt: new Date('2023-10-25T13:30:00Z'),
    seo: { keywords: ['dasara', 'mysuru', 'festival'], metaDescription: 'All about the grand Dasara preparations in Mysuru.' },
    views: 890,
  },
  {
    id: '3',
    title: 'Karnataka Budget 2024: Key Highlights for Tech Sector',
    content: 'The state budget has allocated significant funds for the technology sector, with a focus on startups and AI research.',
    imageUrl: 'https://picsum.photos/800/600',
    "data-ai-hint": 'technology finance',
    author: 'Admin User',
    authorId: 'admin1',
    categoryIds: ['2', '5'],
    districtId: '1',
    status: 'published',
    publishedAt: new Date('2023-10-24T12:00:00Z'),
    createdAt: new Date('2023-10-24T11:00:00Z'),
    updatedAt: new Date('2023-10-24T11:30:00Z'),
    seo: { keywords: ['budget', 'karnataka', 'tech'], metaDescription: 'Key highlights of the Karnataka budget for the tech industry.' },
    views: 2300,
  },
  {
    id: '4',
    title: 'Coastal Karnataka on High Alert for Monsoon Fury',
    content: 'Heavy rains are predicted for the coastal districts of Mangaluru and Udupi. Authorities have issued warnings to fishermen and residents.',
    imageUrl: 'https://picsum.photos/800/600',
    "data-ai-hint": 'stormy coast',
    author: 'Editor User',
    authorId: 'editor1',
    categoryIds: ['6'],
    districtId: '3',
    status: 'published',
    publishedAt: new Date('2023-10-23T18:00:00Z'),
    createdAt: new Date('2023-10-23T17:00:00Z'),
    updatedAt: new Date('2023-10-23T17:30:00Z'),
    seo: { keywords: ['monsoon', 'mangalore', 'udupi'], metaDescription: 'Coastal Karnataka braces for heavy monsoon rains.' },
    views: 740,
  },
  {
    id: '5',
    title: 'Royal Challengers Bangalore Unveil New Jersey',
    content: 'The city\'s beloved IPL team, RCB, has unveiled their new jersey for the upcoming season, featuring a bold new design.',
    imageUrl: 'https://picsum.photos/800/600',
    "data-ai-hint": 'sports team',
    author: 'Admin User',
    authorId: 'admin1',
    categoryIds: ['3'],
    districtId: '1',
    status: 'draft',
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    seo: { keywords: ['rcb', 'ipl', 'cricket'], metaDescription: 'RCB reveals their new look for the next IPL season.' },
    views: 0,
  }
];
